const tshirts = [
  {
    id: 1,
    name: 'A&D',
    year: '2016',
    source: '/images/IMG_0403.JPEG',
    current: false,
    description: 'I started work at Ackmann & Dickenson in 2016.',
    tags: ['all', 'workplace', 'tech'],
    information: {
      test: 'some text',
    },
  },
  {
    id: 2,
    name: 'Minnestar',
    year: '2014',
    source: '/images/IMG_0428.JPEG',
    reverse: '/images/IMG_0429.JPEG',
    current: false,
    description: '',
    tags: ['all', 'tech', 'conference'],
    information: {},
  },
  {
    id: 3,
    name: 'Flywheel',
    year: '2014',
    source: '/images/IMG_0430.JPEG',
    reverse: '/images/IMG_0431.JPEG',
    current: false,
    description: '',
    tags: ['all', 'tech', 'swag'],
    information: {},
  },
  {
    id: 4,
    name: 'Minnebar',
    year: '2013',
    source: '/images/IMG_0432.JPEG',
    reverse: '/images/IMG_0433.JPEG',
    current: false,
    description: '',
    tags: ['all', 'tech', 'conference'],
    information: {},
  },
  {
    id: 5,
    name: 'TBS',
    year: '2017',
    source: '/images/IMG_0434.JPEG',
    reverse: '/images/IMG_0435.JPEG',
    current: false,
    description: '',
    tags: ['all', 'band'],
    information: {},
  },
  {
    id: 6,
    name: 'Minnebar',
    year: '2014',
    source: '/images/IMG_0436.JPEG',
    reverse: '/images/IMG_0436.JPEG',
    current: false,
    description: '',
    tags: ['all', 'tech', 'conference'],
    information: {},
  },
  {
    id: 7,
    name: 'WordCamp',
    year: '2014',
    source: '/images/IMG_0437.JPEG',
    reverse: '/images/IMG_0438.JPEG',
    current: false,
    description: '',
    tags: ['all', 'tech', 'conference'],
    information: {},
  },
  {
    id: 8,
    name: 'DBZ',
    year: '2020',
    source: '/images/IMG_0439.JPEG',
    reverse: '/images/IMG_0440.JPEG',
    current: false,
    description: '',
    tags: ['all', 'misc'],
    information: {},
  },
  {
    id: 9,
    name: 'WordCamp',
    year: '2015',
    source: '/images/IMG_0441.JPEG',
    reverse: '/images/IMG_0442.JPEG',
    current: false,
    description: '',
    tags: ['all', 'tech', 'conference'],
    information: {},
  },
  {
    id: 10,
    name: 'WordCamp Maui',
    year: '2015',
    source: '/images/IMG_0443.JPEG',
    reverse: '/images/IMG_0444.JPEG',
    current: false,
    description: '',
    tags: ['all', 'tech', 'conference'],
    information: {},
  },
  {
    id: 11,
    name: 'Open Streets',
    year: '2014',
    source: '/images/IMG_0445.JPEG',
    reverse: '/images/IMG_0446.JPEG',
    current: false,
    description: '',
    tags: ['all', 'misc'],
    information: {},
  },
  {
    id: 12,
    name: 'Remax',
    year: '2020',
    source: '/images/IMG_0450.JPEG',
    reverse: '/images/IMG_0451.JPEG',
    current: false,
    description: '',
    tags: ['all', 'swag'],
    information: {},
  },
  {
    id: 13,
    name: 'Grandma\'s Marathon',
    year: '2015',
    source: '/images/IMG_0452.JPEG',
    reverse: '/images/IMG_0453.JPEG',
    current: false,
    description: '',
    tags: ['all', 'misc'],
    information: {},
  },
  {
    id: 14,
    name: 'Beachbody Tech',
    year: '2018',
    source: '/images/IMG_0454.JPEG',
    reverse: '/images/IMG_0455.JPEG',
    current: false,
    description: '',
    tags: ['all', 'workplace', 'tech'],
    information: {},
  },
  {
    id: 15,
    name: 'Blink 182',
    year: '2001',
    source: '/images/IMG_0456.JPEG',
    reverse: '/images/IMG_0457.JPEG',
    current: false,
    description: '',
    tags: ['all', 'band'],
    information: {},
  },
  {
    id: 16,
    name: 'ChocoTaco',
    year: '2018',
    source: '/images/IMG_0458.JPEG',
    reverse: '/images/IMG_0459.JPEG',
    current: false,
    description: '',
    tags: ['all', 'misc'],
    information: {},
  },
  {
    id: 17,
    name: 'Ad League',
    year: '2020',
    source: '/images/IMG_0460.JPEG',
    reverse: '/images/IMG_0461.JPEG',
    current: false,
    description: '',
    tags: ['all', 'misc'],
    information: {},
  },
  {
    id: 18,
    name: 'Prestige',
    year: '2015',
    source: '/images/IMG_0462.JPEG',
    reverse: '/images/IMG_0463.JPEG',
    current: false,
    description: '',
    tags: ['all', 'tech'],
    information: {},
  },
  {
    id: 19,
    name: 'Dead to Fall',
    year: '2015',
    source: '/images/IMG_0462.JPEG',
    reverse: '/images/IMG_0463.JPEG',
    current: false,
    description: '',
    tags: ['all', 'band'],
    information: {},
  },
  {
    id: 20,
    name: 'Minnebar',
    year: '2013',
    source: '/images/IMG_0466.JPEG',
    reverse: '/images/IMG_0467.JPEG',
    current: false,
    description: '',
    tags: ['all', 'tech', 'conference'],
    information: {},
  },
  {
    id: 21,
    name: 'WordCamp Milwaukee',
    year: '2015',
    source: '/images/IMG_0468.JPEG',
    reverse: '/images/IMG_0469.JPEG',
    current: false,
    description: '',
    tags: ['all', 'tech', 'conference'],
    information: {},
  },
];

export default tshirts;